export enum ErrorCode {
  PACK_NOT_FOUND = 'PACK_NOT_FOUND',
  SCENARIO_NOT_FOUND = 'SCENARIO_NOT_FOUND',
  VERSION_NOT_FOUND = 'VERSION_NOT_FOUND',
  TEMPLATE_NOT_FOUND = 'TEMPLATE_NOT_FOUND',
  AGENT_NOT_FOUND = 'AGENT_NOT_FOUND',
  INVALID_SCENARIO_REF = 'INVALID_SCENARIO_REF',
  INVALID_PACK_DATA = 'INVALID_PACK_DATA',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  COMPILATION_ERROR = 'COMPILATION_ERROR',
  CONTROL_PLANE_UNAVAILABLE = 'CONTROL_PLANE_UNAVAILABLE',
  INTERNAL_ERROR = 'INTERNAL_ERROR'
}
